# Generated by Django 4.0.6 on 2022-07-18 19:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import zmq.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tast_name', models.CharField(blank=True, choices=[('A1C Test', 'A1C Test'), ('Fasting Blood Sugar Test', 'Fasting Blood Sugar Test'), ('Glucose Tolerance Test', 'Glucose Tolerance Test'), ('Random Blood Sugar Test', 'Random Blood Sugar Test'), ('Tests for Gestational Diabetes', 'Tests for Gestational Diabetes'), ('Glucose Screening Test', 'Glucose Screening Test'), ('Glucose Tolerance Test', 'Glucose Tolerance Test'), ('Prevent Type 2 Diabetes', 'Prevent Type 2 Diabetes'), ('Diabetes Treatment Plan', 'Diabetes Treatment Plan')], default=zmq.constants.SecurityMechanism['NULL'], max_length=200, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('diatype', models.CharField(blank=True, choices=[('type1', 'type1'), ('type2', 'type2')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medecin_name', models.CharField(blank=True, choices=[('Actos ', 'Actos '), ('Actrapid', 'Actrapid'), ('Augmentin ', 'Augmentin '), ('Amaryl ', 'Amaryl '), ('Byetta ', 'Byetta '), ('Bydreoun', 'Bydreoun'), ('Competact', 'Competact'), ('Diamicron ', 'Diamicron '), ('Eucreas ', 'Eucreas '), ('Forxiga ', 'Forxiga '), ('Galvus ', 'Galvus '), ('Gliclazide', 'Gliclazide'), ('Glucobay ', 'Glucobay '), ('Humalog ', 'Humalog '), ('Humulin I', 'Humulin I'), ('Hypurin Bovine Isophane', 'Hypurin Bovine Isophane'), ('Hypurin Bovine Lente ', 'Hypurin Bovine Lente '), ('Hypurin Bovine Protamine Zinc', 'Hypurin Bovine Protamine Zinc'), ('Insulin Glulisine ', 'Insulin Glulisine '), ('Insuman Basal ', 'Insuman Basal '), ('Insuman Comb ', 'Insuman Comb '), ('Janumet ', 'Janumet '), ('Januvia ', 'Januvia '), ('Lantus ', 'Lantus '), ('Lucentis', 'Lucentis'), ('Lyxumia ', 'Lyxumia '), ('Metformin', 'Metformin'), ('NovoRapid ', 'NovoRapid '), ('Prandin ', 'Prandin '), ('Starlix ', 'Starlix '), ('Trulicity', 'Trulicity'), ('Victoza ', 'Victoza ')], default=zmq.constants.SecurityMechanism['NULL'], max_length=200, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
